<a href="https://colab.research.google.com/github/Kaushal-Top5699/tensorflow_04/blob/main/tensorflow_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Matrix Multipliation**

In [21]:
# Matrix multiplication is one of the most common tensor operations.
import tensorflow as tf

In [27]:
# Using matmul we can multiply two martices 
tensor_1 = tf.constant([[1, 2],
                      [4, 5]])

tensor_2 = tf.constant([[1, 2],
                        [4, 5]])
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 12],
       [24, 33]], dtype=int32)>

In [28]:
# If we simply multiply two tensors then it will be element wise
tensor_1 * tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [16, 25]], dtype=int32)>

In [29]:
# (3x3) * (3x2) = (3x2) is the shape of new tensor
tensor_a = tf.constant([[1, 2, 5],
                        [7, 2, 1],
                        [3, 3, 3]])
tensor_b = tf.constant([[3, 5],
                        [6, 7],
                        [1, 8]])

tf.matmul(tensor_a, tensor_b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [31]:
# Matrix multiplication in python
tensor_a @ tensor_b
# We get the same thing

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 12],
       [24, 33]], dtype=int32)>

In [46]:
# The following two tensor's shapes are (3x2) and (3x2) we cannot multiply them, therefore, we reshape one of the tensors into (2x3) and them multiply.
tensor_3 = tf.constant([[3, 5],
                        [6, 7],
                        [1, 8]])
tensor_4 = tf.constant([[3, 5],
                        [6, 7],
                        [1, 8]])
tf.matmul(tensor_3, tf.reshape(tensor_4, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 20, 58],
       [67, 37, 92],
       [59, 13, 70]], dtype=int32)>

In [38]:
# Original and reshaped tensor_4
tensor_4, tf.reshape(tensor_4, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 5, 6],
        [7, 1, 8]], dtype=int32)>)

In [41]:
# We reshape tensor_3 instead of tensor_4, it still works.
tf.reshape(tensor_3, shape=(2, 3)) @ tensor_4
# We get a (2x2) matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 45,  98],
       [ 35, 106]], dtype=int32)>

In [42]:
# Original and reshaped tensor_3
tensor_3, tf.reshape(tensor_3, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 5, 6],
        [7, 1, 8]], dtype=int32)>)

In [49]:
# We can also transpose a matrix.
tensor_3, tf.transpose(tensor_3), tf.reshape(tensor_3, [2, 3])

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 6, 1],
        [5, 7, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 5, 6],
        [7, 1, 8]], dtype=int32)>)

In [50]:
# We can use tranpose to multiply two metrices with same shape, BUT note that transpose is not the same as rehsape. Look at above example.
tensor_4 @ tf.transpose(tensor_3)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[34, 53, 43],
       [53, 85, 62],
       [43, 62, 65]], dtype=int32)>

### **Therefore, we can use tf.matmul() or tf.tensordot(), they both are same thing.**

In [57]:
# Now in order to make tf.tensordot() work, we have to make sure at least one of them should be transpose.
tf.tensordot(tensor_3, tf.transpose(tensor_4), 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[34, 53, 43],
       [53, 85, 62],
       [43, 62, 65]], dtype=int32)>

In [58]:
tf.matmul(tensor_3, tf.transpose(tensor_4))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[34, 53, 43],
       [53, 85, 62],
       [43, 62, 65]], dtype=int32)>

In [59]:
tf.matmul(tensor_3, tf.reshape(tensor_4, [2, 3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[44, 20, 58],
       [67, 37, 92],
       [59, 13, 70]], dtype=int32)>

In [67]:
x = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
y = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

y, tf.reshape(y, [2, 3]), tf.transpose(y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

In [68]:
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>